### ISSUE TITLE
buildArchive?

### ISSUE THREAD

**Issue by yangky11** [lean-dojo/LeanCopilot#55]
Hi @tydeu,

I recently upgraded to the latest Lean `v4.6.0-rc1` and found that now I have to manually add the OS and `tar.gz` to `buildArchive?`. Just wanted to double-check if that's expected.

https://github.com/lean-dojo/LeanCopilot/blob/4bc4e6c09689472e5523b0acc724c666baf51e6e/lakefile.lean#L65

Please see these two commits:
https://github.com/lean-dojo/LeanCopilot/commit/965d4ba033a10735fd6519b94421843d2f23c704
https://github.com/lean-dojo/LeanCopilot/commit/4bc4e6c09689472e5523b0acc724c666baf51e6e

**Comment by tydeu** [comment]
@yangky11 With `4.6.0-rc1`, the default build archive name now includes the architecture, so ideally LeanCopilot should no longer need to customize it. As part of this change, the build archive configuration option was changed to be a complete override, so that users can custom customize this however they want should the default be insufficient. More details are available in the related PR (leanprover/lean4#3226).

**Comment by yangky11** [comment]
thx
