### ISSUE TITLE
CI Failed

### ISSUE THREAD

**Issue by yangky11** [lean-dojo/LeanCopilot#61]
https://github.com/lean-dojo/LeanCopilot/actions/runs/8420847569/job/23057242430

**Comment by Peiyang-Song** [comment]
Thanks, it's probably because x86-64_MacOS is tested but we no longer generate binaries for that architecture. Let me adjust the CI to fix it.

**Comment by Peiyang-Song** [comment]
The original problem should have been fixed in Commit [b983b89](https://github.com/lean-dojo/LeanCopilot/commit/b983b89c2d75217d15bf6ed0235fc25df0e740e6). Another problem is revealed when running the test for using LeanCopilot in an external project on `ubuntu-latest`, where `lake build` fails with no helpful log even in the verbose mode. The problem is pretty weird as testing on exactly the same platform with the same steps leads to no errors at all. I'm looking more into it.

**Comment by yangky11** [comment]
Looks like it's working now.

**Comment by Peiyang-Song** [comment]
Yeah it works now. PR #65 resolves the last few warnings.
